from pathlib import Path

from docx import Document


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Strategic Importance Premiums in Geopolitical Market Shocks.codex-working.docx"
OUT = ROOT / "Strategic Importance Premiums in Geopolitical Market Shocks - citation-edited.docx"


REPLACEMENTS = {
    97: "This chapter presents the theoretical framework for the dissertation. The central question is when geopolitical competition generates positive market reactions for strategically important firms or sectors through expected state support. The theory does not claim that geopolitical competition is generally beneficial for markets. It begins from the opposite premise: geopolitical competition often increases uncertainty, raises compliance costs, restricts market access, disrupts supply chains, and produces negative aggregate market effects, consistent with the geopolitical-risk literature (Caldara & Iacoviello, 2022). The puzzle is that selected firms may nevertheless experience positive market reactions when geopolitical competition leads states to provide credible support to strategically important actors. The argument is organised around a conditional pathway: Geopolitical Competition → Strategic Importance → State Support → Investor Interpretation → Positive Market Reaction.",
    98: "The mechanism is state support. Strategic importance identifies which firms, sectors, technologies, or locations become salient to governments under geopolitical competition. However, strategic importance alone does not guarantee positive market reactions. A strategically important firm may still face export restrictions, retaliation, input disruption, or costly compliance obligations. Positive market reactions become more likely when strategic importance is converted into credible state support, and when investors interpret that support as improving expected cash flows or reducing downside risk. This logic connects industrial-policy scholarship on state support and strategic sectors with finance scholarship on market reactions to information (Fama, 1970; Fama et al., 1969; Mazzucato, 2013, 2021; Rodrik, 2004). The frozen theoretical claim is narrow: Geopolitical competition generates positive market reactions when strategically important firms or sectors are expected to receive credible state support that improves future cash flows or reduces downside risk. This chapter develops that claim without expanding the theory beyond the frozen project logic.",
    100: "The standard expectation in much work on geopolitical risk is that geopolitical competition creates market losses. Rivalry among states can increase uncertainty, disrupt trade and investment, restrict technology flows, and reduce confidence in future earnings. Wars, sanctions, export controls, investment restrictions, and strategic decoupling can all produce risk-off reactions in financial markets (Caldara & Iacoviello, 2022; Farrell & Newman, 2019). This risk pathway can be summarised as: Geopolitical Competition → Threat / Restriction / Uncertainty → Negative Market Reaction.",
    104: "Geopolitical competition refers to rivalry among states using military, economic, technological, regulatory, and industrial-policy tools to pursue security, influence, autonomy, or strategic advantage. In this project, the relevant events are not generic diplomatic tensions. The empirical focus is on policy-relevant actions such as subsidies, procurement commitments, export controls, industrial-policy announcements, strategic investment, and supply-chain restrictions. This definition draws on economic statecraft and geoeconomics scholarship that treats markets, trade, finance, and supply chains as instruments and arenas of strategic power (Baldwin, 1985; Blackwill & Harris, 2016; Farrell & Newman, 2019, 2023; Hirschman, 1980; Luttwak, 1990).",
    108: "Strategic importance is the degree to which a firm, sector, technology, or location is viewed by governments as important for national security, technological leadership, economic resilience, military capability, or control over critical supply chains. Strategic importance is a scope condition in the theory. It identifies where states are likely to care, but it does not itself create the market mechanism. This distinction follows from industrial policy and developmental-state scholarship, which shows why states may prioritise strategic sectors without implying that every policy signal immediately produces a positive market reaction (Amsden, 1989, 2001; Chang, 2002; Johnson, 1982; Wade, 1990).",
    113: "State support is the core conversion mechanism in the theory. It refers to government action that plausibly improves the expected economic position of strategically important firms or sectors. It includes subsidies, procurement, grants, tax credits, loans, guarantees, regulation, protection, industrial policy, local-content rules, trusted-supplier rules, and strategic capacity commitments. This mechanism builds on industrial-policy and mission-oriented state arguments that public institutions can shape markets, investment incentives, and innovation trajectories (Block & Keller, 2011; Mazzucato, 2013, 2021; Rodrik, 2004; Weiss, 2014).",
    118: "Investor interpretation is the final step before market reaction. Geopolitical events are not automatically classified by markets as either threats or opportunities. They may contain both signals at once. A state-support announcement may imply future subsidies and protected demand, but it may also signal high costs, political constraints, or prior weakness. An export-control event may threaten exposed firms, but it may also imply substitution opportunities for competitors. This interpretive step is consistent with finance theory's emphasis on price reactions to information and behavioural finance's emphasis on narratives and uncertainty in investor judgment (Fama, 1970; Fama et al., 1969; Shiller, 2003).",
    122: "Market reaction refers to short-window changes in firm or sector value around policy-relevant geopolitical events. The dissertation focuses on abnormal returns rather than long-term welfare, policy success, or realised productivity. The outcome captures investor expectations at the time of the event. This approach follows the event-study tradition, which uses short-window price movements to infer the market's assessment of new information (Brown & Warner, 1985; MacKinlay, 1997).",
    136: "This chapter explains the empirical design used to evaluate the State Support mechanism. The dissertation uses a small-sample event-study design focused on semiconductor state-support announcements and related event-firm observations. The design is intended as a transparent market-expectations test, not a structural causal estimate. It does not claim to identify the full causal effect of geopolitical competition on firm value. Instead, it tests whether named state-support announcements for strategically important semiconductor firms are associated with short-window market reactions consistent with the frozen theory. This design follows the event-study logic that prices can react to new information around identifiable events (Brown & Warner, 1985; Fama, 1970; MacKinlay, 1997).",
    137: "The design follows the pre-committed logic of the project. Events, assets, event-asset links, coding rules, and outcome variables were defined before interpreting returns. This discipline responds to concerns about researcher degrees of freedom, post hoc outcome selection, and undisclosed analytic flexibility (Gelman & Loken, 2014; Nosek et al., 2018; Simmons et al., 2011). The empirical strategy prioritises sector-adjusted returns because the main concern is whether named beneficiaries move differently from the broader semiconductor sector.",
    153: "The dataset is organised around the event-asset pair. This unit of analysis is necessary because the same event may have different implications for different firms. For example, a state-support announcement may name one beneficiary while also affecting competitors, suppliers, benchmarks, or sector peers. The dataset contains 5 core components.",
    157: "The dissertation uses an event-study design to measure short-window market reactions around policy announcements. The purpose is to evaluate whether investors reacted to state-support announcements in a way consistent with the State Support mechanism. Event-study methodology is appropriate because the project examines identifiable announcements and short-window abnormal returns, while also recognizing that policy events can be anticipated or confounded (Brown & Warner, 1985; Kothari & Warner, 2007; MacKinlay, 1997).",
    160: "The sector adjustment is central to the design. A named beneficiary may rise because the entire semiconductor sector rose, not because investors interpreted state support as firm-specific opportunity. The sector-adjusted return therefore provides a stricter test than broad market adjustment alone. This choice applies the event-study principle that the benchmark should help separate event-specific information from broader market or sector movement (Campbell et al., 1997; MacKinlay, 1997).",
    166: "This distinction is important because wider windows are more exposed to confounding news, sector movement, earnings expectations, macroeconomic conditions, and anticipation effects. The research design therefore prioritises the short sector-adjusted window while reporting other measures only as supplementary evidence. The treatment of wider windows as descriptive follows the event-study caution that longer windows can make attribution more difficult (Kothari & Warner, 2007; MacKinlay, 1997).",
    172: "This classification rule is designed to prevent post hoc reinterpretation. If a named beneficiary does not outperform the semiconductor benchmark, the result cannot be rescued by pointing only to broad-market outperformance or wider-window movement. Anticipation, support-as-weakness, and market complexity may be discussed as limitations, but they do not change the classification of the primary outcome. This rule operationalises the dissertation's commitment to transparency and restricted analytic flexibility (Gelman & Loken, 2014; Nosek et al., 2018; Simmons et al., 2011).",
    180: "Second, the semiconductor and AI cycle may confound market reactions. Semiconductor firms in 2023 and 2024 were affected by demand expectations, AI investment, capacity cycles, and earnings revisions. Sector adjustment using SMH reduces but does not eliminate this concern. Third, state support may signal weakness rather than opportunity. A firm receiving public support may be viewed as strategically important but commercially challenged. The design treats underperformance relative to sector benchmarks as theory-weakening for the event rather than explaining it away. These issues are consistent with standard event-study concerns about confounding information and benchmark choice (Brown & Warner, 1985; Kothari & Warner, 2007).",
    190: "The primary validated output file is data/event_firm_returns.csv. The validation artefact is data/local_price_validation_report.md. The local validation report confirms that the event-study pipeline was run for the three focal primary event-firm rows: E009 / INTC, E010 / TSM, and E012 / MU. These observations correspond to the Intel CHIPS Act preliminary terms announcement, the TSMC Arizona CHIPS Act preliminary terms announcement, and the Micron CHIPS Act preliminary agreement announcement.",
    212: "This section reports the recipient versus non-recipient comparison from the locked evidence package. The comparison is descriptive. It summarises CAR values by whether the linked firm observation is classified as a recipient or non-recipient in the validated support-event audit. Table 5.4 reports the recipient and non-recipient summary values.",
    227: "The primary empirical test used car_sector_m1_p1, the sector-adjusted cumulative abnormal return over the [-1,+1] event window. This outcome was pre-committed as the primary evidence variable because it compares the named beneficiary against the semiconductor-sector benchmark. The classification rule was also fixed before interpretation: observations above +0.25 percentage points are classified as supportive, observations between -0.25 and +0.25 percentage points are classified as null, and observations below -0.25 percentage points are classified as theory-weakening. This interpretation follows the event-study logic developed in Chapter 4 and avoids shifting to more favorable windows after observing the results (Gelman & Loken, 2014; MacKinlay, 1997; Nosek et al., 2018).",
    236: "The wider-window descriptive results provide context but do not alter the primary classifications. CAR[-7,+7] was not the pre-committed primary outcome. It is reported descriptively because it shows wider event-window movement, but it is more vulnerable to confounding news and broader market conditions than the short sector-adjusted window. For that reason, the Chapter 5 descriptive exhibits should be read as supplementary to the primary outcome, not as replacements for it (Kothari & Warner, 2007; MacKinlay, 1997).",
    240: "The frozen theory defines Strategic Importance as a scope condition, State Support as the mechanism, Investor Interpretation as the transmission process, and Positive Market Reaction as the outcome. The evidence does not require changing this framework, but it does limit what can be claimed about it. This interpretation is consistent with the literature synthesis in Chapter 2: geopolitical risk, economic statecraft, industrial policy, and market-reaction literatures each explain part of the causal chain, but the dissertation tests whether those parts combine empirically in observable market reactions.",
    249: "The 3rd limitation is event-study identification. Policy announcements may be anticipated before the official event date. Market participants may price information gradually through negotiations, media reports, prior investment commitments, or earlier policy signals. A short-window event study can capture market reactions around observable announcements, but it cannot eliminate anticipation concerns. This is a standard limitation of event-study designs, especially when policy events are partly public before formal announcement dates (Kothari & Warner, 2007; MacKinlay, 1997).",
    253: "The final limitation concerns interpretation. Market reactions are not long-term policy outcomes. A positive abnormal return does not show that state support improves productivity, social welfare, industrial capacity, or national security. A negative abnormal return does not prove that support has no long-term value. The analysis is limited to investor expectations around event windows, consistent with the distinction between market reaction and long-run policy evaluation in the event-study framework.",
    259: "A fourth direction is to add text evidence on Investor Interpretation. Analyst reports, earnings-call language, financial media, and corporate statements could help identify whether investors and firms framed support as opportunity, cost offset, weakness signal, or strategic protection. Such evidence would not replace event-study outcomes, but it could help clarify the transmission process between State Support and market reaction. It would also address the interpretive gap between observed prices and the narratives investors use when evaluating mixed geopolitical-policy signals (Shiller, 2003).",
    265: "What the dissertation does provide is a disciplined test of the State Support mechanism using frozen theory, frozen coding, a pre-committed primary outcome, and validated event-study outputs. The evidence supports a limited conclusion: state-backed opportunity is empirically uneven. It appears in one primary case and is weakened in two others under the dissertation's own classification rule. The strongest contribution is therefore not a broad confirmation of the theory, but a transparent demonstration of how the State Support mechanism can be tested, constrained, and evaluated against evidence.",
    278: "Amsden, A. H. (1989). Asia's next giant: South Korea and late industrialization. Oxford",
    300: "Evans, P. (1995). Embedded autonomy: States and industrial transformation. Princeton",
    301: "University Press.",
}


def replace_paragraph_text(paragraph, text):
    if not paragraph.runs:
        paragraph.add_run(text)
        return
    paragraph.runs[0].text = text
    for run in paragraph.runs[1:]:
        run.text = ""


def main():
    doc = Document(SOURCE)
    for idx, new_text in REPLACEMENTS.items():
        replace_paragraph_text(doc.paragraphs[idx], new_text)
    doc.save(OUT)
    print(OUT)


if __name__ == "__main__":
    main()
